# Use the official Node.js 18 image as base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular application
RUN npm run build

# Expose the port on which the server will run
EXPOSE 4000

# Command to run the Angular server with server-side rendering
CMD ["npm", "run", "serve:ssr:init-app"]
