sonar.projectKey=air-account-be
sonar.projectName=Air Account BE
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.sourceEncoding=UTF-8
sonar.host.url=http://157.245.136.36:9000
